import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./styles/globals.css";
import { ContainerLayout } from "@/components";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Chef Burguer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={roboto.className}>
        <ContainerLayout>
        {children}
        </ContainerLayout>
      </body>
    </html>
  );
}